sudo: requred
language: ruby
script: rake spec:travis
before_script:
  - travis_retry rake -E 'module ::Bundler; VERSION = "0.0.0"; end' override_version
  - travis_retry rake spec:travis:deps
  - travis_retry rake man:build
  - travis_retry rake spec:rubygems:clone_rubygems_$RGV

rvm:
  - 2.5.1
env:
  - RGV=v2.7.4

matrix:
  include:
    - rvm: 2.5.1
      env: RGV=v2.6.14
