sudo: requred
language: ruby
script: rake spec:travis
before_script:
  - travis_retry rake spec:travis:deps
  - travis_retry rake override_version
  - travis_retry rake man:build
  - travis_retry rake spec:rubygems:clone_rubygems_$RGV

# temporary workaround for https://github.com/travis-ci/travis-ci/issues/8892
group: deprecated-2017Q4

rvm:
  - 2.4.1

matrix:
  include:
    - rvm: 2.4.1
      env: RGV=v2.6.8 BUNDLER_SPEC_SUB_VERSION=2.0.0
